# Generated by Django 5.2 on 2025-04-05 15:59

import business.utils
import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(default='UG', max_length=2)),
                ('address', models.CharField(max_length=255)),
                ('primary_phone_contact', models.CharField(max_length=20, validators=[business.utils.validate_international_phone_number])),
                ('alternative_phone_contact', models.CharField(max_length=20, validators=[business.utils.validate_international_phone_number])),
                ('primary_email_contact', models.EmailField(max_length=254)),
                ('alternative_email_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('tax_Id_number', models.CharField(blank=True, max_length=255, null=True)),
                ('accounts_currency', models.CharField(default='UGX', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('business_logo', models.ImageField(blank=True, null=True, upload_to='business_logo/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
