# Generated by Django 5.2 on 2025-04-05 16:07

import business.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='company_registration_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='contacts_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='registration_information_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('primary_phone_contact', models.CharField(max_length=20, validators=[business.utils.validate_international_phone_number])),
                ('alternative_phone_contact', models.CharField(blank=True, max_length=20, null=True, validators=[business.utils.validate_international_phone_number])),
                ('tax_Id_number', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('company_registration_number', models.CharField(blank=True, max_length=255, null=True)),
                ('is_institution', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('registration_number_verified', models.BooleanField(default=False)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_customers', to='business.business')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('altitude', models.DecimalField(blank=True, decimal_places=7, max_digits=15, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=15, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=15, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_locations', to='business.business')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
