# Generated by Django 5.2 on 2025-04-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_company_registration_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='registration_number_verified',
            new_name='contacts_verified',
        ),
        migrations.AddField(
            model_name='customer',
            name='registration_information_verified',
            field=models.BooleanField(default=False),
        ),
    ]
