# Generated by Django 5.2 on 2025-04-05 16:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_rename_registration_number_verified_customer_contacts_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('altitude', models.DecimalField(blank=True, decimal_places=7, max_digits=15, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=15, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=15, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_locations', to='business.customer')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
