# Generated by Django 5.2 on 2025-04-05 16:18

import business.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_customerlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPersonnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('national_Id_number', models.CharField(blank=True, max_length=255, null=True)),
                ('refugee_Id_number', models.CharField(blank=True, max_length=255, null=True)),
                ('passport_Id_number', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(max_length=255)),
                ('primary_phone_contact', models.CharField(max_length=20, validators=[business.utils.validate_international_phone_number])),
                ('alternative_phone_contact', models.CharField(blank=True, max_length=20, null=True, validators=[business.utils.validate_international_phone_number])),
                ('primary_email_contact', models.EmailField(max_length=254)),
                ('alternative_email_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_finance_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('contacts_verified', models.BooleanField(default=False)),
                ('registration_information_verified', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_personnel', to='business.customer')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
