# Generated by Django 5.2 on 2025-04-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_product_inventory_productcategory_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_suspended',
            field=models.BooleanField(default=True),
        ),
    ]
